{"name": "test_rerun_with_condition", "status": "broken", "statusDetails": {"message": "TypeError: _FlakyPlugin._make_test_flaky() got an unexpected keyword argument 'reruns'", "trace": ">       lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n                ^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n\n.venv/lib/python3.11/site-packages/flaky/flaky_pytest_plugin.py:146: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <flaky.flaky_pytest_plugin.FlakyPlugin object at 0x104b5ab50>, item = <Function test_rerun_with_condition>\n\n    def pytest_runtest_setup(self, item):\n        \"\"\"\n        Pytest hook to modify the test before it's run.\n    \n        :param item:\n            The test item.\n        \"\"\"\n        if not self._has_flaky_attributes(item):\n            if hasattr(item, 'iter_markers'):\n                for marker in item.iter_markers(name='flaky'):\n>                   self._make_test_flaky(item, *marker.args, **marker.kwargs)\nE                   TypeError: _FlakyPlugin._make_test_flaky() got an unexpected keyword argument 'reruns'\n\n.venv/lib/python3.11/site-packages/flaky/flaky_pytest_plugin.py:255: TypeError"}, "start": 1751219706409, "stop": 1751219706409, "uuid": "d00e7cd0-9292-4226-9f28-3fe6c575bf60", "historyId": "431c2bc8b3d1acdf6a5f6ac2f94650a9", "testCaseId": "431c2bc8b3d1acdf6a5f6ac2f94650a9", "fullName": "tests.pytest.test_reruns#test_rerun_with_condition", "labels": [{"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_reruns"}, {"name": "host", "value": "MacBook-Pro-Tochka-2.local"}, {"name": "thread", "value": "88573-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_reruns"}]}