{"name": "Delete file", "status": "broken", "statusDetails": {"message": "NameError: name 'Draft202012Validator' is not defined", "trace": "self = <tests.files.test_files.TestFiles object at 0x107555a90>, files_client = <clients.files.files_client.FilesClient object at 0x10788a590>\nfunction_file = FileFixture(request=CreateFileRequestSchema(filename='0ea9c72f-5386-4e6e-8bb6-218585f01cd4.png', directory='tests', up...s/0ea9c72f-5386-4e6e-8bb6-218585f01cd4.png'), filename='0ea9c72f-5386-4e6e-8bb6-218585f01cd4.png', directory='tests')))\n\n    @allure.title(\"Delete file\")\n    @allure.story(AllureStory.DELETE_ENTITY)\n    @allure.sub_suite(AllureStory.DELETE_ENTITY)\n    def test_delete_file(self, files_client: FilesClient, function_file: FileFixture):\n        # 1. Удаляем файл\n        delete_response = files_client.delete_file_api(function_file.response.file.id)\n        # 2. Проверяем, что файл успешно удален (статус 200 OK)\n        assert_status_code(delete_response.status_code, HTTPStatus.OK)\n    \n        # 3. Пытаемся получить удаленный файл\n        get_response = files_client.get_file_api(function_file.response.file.id)\n        get_response_data = InternalErrorResponseSchema.model_validate_json(get_response.text)\n    \n        # 4. Проверяем, что сервер вернул 404 Not Found\n        assert_status_code(get_response.status_code, HTTPStatus.NOT_FOUND)\n        # 5. Проверяем, что в ответе содержится ошибка \"File not found\"\n        assert_file_not_found_response(get_response_data)\n    \n>       validate_json_schema(get_response.json(), get_response_data.model_json_schema())\n\ntests/files/test_files.py:112: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ninstance = {'detail': 'File not found'}\nschema = {'description': 'Модель для описания внутренней ошибки.', 'properties': {'detail': {'title': 'Detail', 'type': 'string'}}, 'required': ['detail'], 'title': 'InternalErrorResponseSchema', ...}\n\n    @allure.step(\"Validating JSON schema\")\n    def validate_json_schema(instance: Any, schema: dict) -> None:\n        \"\"\"\n        Проверяет, соответствует ли JSON-объект (instance) заданной JSON-схеме (schema).\n    \n        :param instance: JSON-данные, которые нужно проверить.\n        :param schema: Ожидаемая JSON-schema.\n        :raises jsonschema.exceptions.ValidationError: Если instance не соответствует schema.\n        \"\"\"\n        # Логируем факт начала валидации\n        logger.info(\"Validating JSON schema\")\n    \n        validate(\n            schema=schema,\n            instance=instance,\n>           format_checker=Draft202012Validator.FORMAT_CHECKER,\n                           ^^^^^^^^^^^^^^^^^^^^\n        )\nE       NameError: name 'Draft202012Validator' is not defined\n\ntools/assertions/schema.py:25: NameError"}, "steps": [{"name": "Delete file by id 'd82438ad-2d15-4eaa-a6d6-f1604fdc0b13'", "status": "passed", "steps": [{"name": "Make DELETE request to '/api/v1/files/d82438ad-2d15-4eaa-a6d6-f1604fdc0b13'", "status": "passed", "attachments": [{"name": "cURL command", "source": "77cfca7b-9b96-4be3-b6db-afdf08f05992-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "url", "value": "'/api/v1/files/d82438ad-2d15-4eaa-a6d6-f1604fdc0b13'"}], "start": 1752506427499, "stop": 1752506427510}], "parameters": [{"name": "file_id", "value": "'d82438ad-2d15-4eaa-a6d6-f1604fdc0b13'"}], "start": 1752506427499, "stop": 1752506427510}, {"name": "Check that response status code equals to <HTTPStatus.OK: 200>", "status": "passed", "parameters": [{"name": "actual", "value": "200"}, {"name": "expected", "value": "<HTTPStatus.OK: 200>"}], "start": 1752506427510, "stop": 1752506427510}, {"name": "Get file by id 'd82438ad-2d15-4eaa-a6d6-f1604fdc0b13'", "status": "passed", "steps": [{"name": "Make GET request to '/api/v1/files/d82438ad-2d15-4eaa-a6d6-f1604fdc0b13'", "status": "passed", "attachments": [{"name": "cURL command", "source": "1794dce4-9963-4cc8-9c56-36649da5c5ef-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "url", "value": "'/api/v1/files/d82438ad-2d15-4eaa-a6d6-f1604fdc0b13'"}, {"name": "params", "value": "None"}], "start": 1752506427510, "stop": 1752506427515}], "parameters": [{"name": "file_id", "value": "'d82438ad-2d15-4eaa-a6d6-f1604fdc0b13'"}], "start": 1752506427510, "stop": 1752506427515}, {"name": "Check that response status code equals to <HTTPStatus.NOT_FOUND: 404>", "status": "passed", "parameters": [{"name": "actual", "value": "404"}, {"name": "expected", "value": "<HTTPStatus.NOT_FOUND: 404>"}], "start": 1752506427516, "stop": 1752506427516}, {"name": "Check file not found response", "status": "passed", "steps": [{"name": "Check internal error response", "status": "passed", "steps": [{"name": "Check that 'details' equals to 'File not found'", "status": "passed", "parameters": [{"name": "actual", "value": "'File not found'"}, {"name": "expected", "value": "'File not found'"}, {"name": "name", "value": "'details'"}], "start": 1752506427516, "stop": 1752506427516}], "parameters": [{"name": "actual", "value": "InternalErrorResponseSchema(details='File not found')"}, {"name": "expected", "value": "InternalErrorResponseSchema(details='File not found')"}], "start": 1752506427516, "stop": 1752506427516}], "parameters": [{"name": "actual", "value": "InternalErrorResponseSchema(details='File not found')"}], "start": 1752506427516, "stop": 1752506427516}, {"name": "Validating JSON schema", "status": "broken", "statusDetails": {"message": "NameError: name 'Draft202012Validator' is not defined\n", "trace": "  File \"/Users/basmakovoleg/my-git-projects/autotests-api/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/basmakovoleg/my-git-projects/autotests-api/tools/assertions/schema.py\", line 25, in validate_json_schema\n    format_checker=Draft202012Validator.FORMAT_CHECKER,\n                   ^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "instance", "value": "{'detail': 'File not found'}"}, {"name": "schema", "value": "{'description': 'Модель для описания внутренней ошибки.', 'properties': {'detail': {'title': 'Detail', 'type': 'string'}}, 'required': ['detail'], 'title': 'InternalErrorResponseSchema', 'type': 'object'}"}], "start": 1752506427517, "stop": 1752506427517}], "attachments": [{"name": "log", "source": "c46eab0d-c096-431b-84aa-4f28abaef685-attachment.txt", "type": "text/plain"}], "start": 1752506427499, "stop": 1752506427517, "uuid": "76fc1d99-4c14-4581-a5dd-242c6b528cf3", "historyId": "27e018525da6e38db441922bcd4d0724", "testCaseId": "27e018525da6e38db441922bcd4d0724", "fullName": "tests.files.test_files.TestFiles#test_delete_file", "labels": [{"name": "tag", "value": "REGRESSION"}, {"name": "story", "value": "Delete entity"}, {"name": "parentSuite", "value": "LMS service"}, {"name": "subSuite", "value": "Delete entity"}, {"name": "epic", "value": "LMS service"}, {"name": "suite", "value": "Files"}, {"name": "feature", "value": "Files"}, {"name": "tag", "value": "FILES"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "files"}, {"name": "host", "value": "MacBook-Pro-Tochka-2.local"}, {"name": "thread", "value": "20295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.files.test_files"}]}