{"name": "test_rerun_1", "status": "broken", "statusDetails": {"message": "TypeError: _FlakyPlugin._make_test_flaky() got an unexpected keyword argument 'reruns'", "trace": ">       lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n                ^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n\n.venv/lib/python3.11/site-packages/flaky/flaky_pytest_plugin.py:146: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <flaky.flaky_pytest_plugin.FlakyPlugin object at 0x10210edd0>, item = <Function test_rerun_1>\n\n    def pytest_runtest_setup(self, item):\n        \"\"\"\n        Pytest hook to modify the test before it's run.\n    \n        :param item:\n            The test item.\n        \"\"\"\n        if not self._has_flaky_attributes(item):\n            if hasattr(item, 'iter_markers'):\n                for marker in item.iter_markers(name='flaky'):\n>                   self._make_test_flaky(item, *marker.args, **marker.kwargs)\nE                   TypeError: _FlakyPlugin._make_test_flaky() got an unexpected keyword argument 'reruns'\n\n.venv/lib/python3.11/site-packages/flaky/flaky_pytest_plugin.py:255: TypeError"}, "start": 1751219673009, "stop": 1751219673009, "uuid": "e22a700e-9629-4998-b91e-3f9368405989", "historyId": "81d6ff8066b3db2379029adbb835c586", "testCaseId": "81d6ff8066b3db2379029adbb835c586", "fullName": "tests.pytest.test_reruns.TestReruns#test_rerun_1", "labels": [{"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_reruns"}, {"name": "subSuite", "value": "TestReruns"}, {"name": "host", "value": "MacBook-Pro-Tochka-2.local"}, {"name": "thread", "value": "88508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_reruns"}]}