{"name": "test_reruns", "status": "broken", "statusDetails": {"message": "TypeError: _FlakyPlugin._make_test_flaky() got an unexpected keyword argument 'reruns'", "trace": ">       lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n                ^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n\n.venv/lib/python3.11/site-packages/flaky/flaky_pytest_plugin.py:146: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <flaky.flaky_pytest_plugin.FlakyPlugin object at 0x10210edd0>, item = <Function test_reruns>\n\n    def pytest_runtest_setup(self, item):\n        \"\"\"\n        Pytest hook to modify the test before it's run.\n    \n        :param item:\n            The test item.\n        \"\"\"\n        if not self._has_flaky_attributes(item):\n            if hasattr(item, 'iter_markers'):\n                for marker in item.iter_markers(name='flaky'):\n>                   self._make_test_flaky(item, *marker.args, **marker.kwargs)\nE                   TypeError: _FlakyPlugin._make_test_flaky() got an unexpected keyword argument 'reruns'\n\n.venv/lib/python3.11/site-packages/flaky/flaky_pytest_plugin.py:255: TypeError"}, "start": 1751219673004, "stop": 1751219673004, "uuid": "5ee30593-a04b-4526-b486-c298f04776d0", "historyId": "8a26534d2d9e195af15b0cb6e3498ee0", "testCaseId": "8a26534d2d9e195af15b0cb6e3498ee0", "fullName": "tests.pytest.test_reruns#test_reruns", "labels": [{"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_reruns"}, {"name": "host", "value": "MacBook-Pro-Tochka-2.local"}, {"name": "thread", "value": "88508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_reruns"}]}